# Generated by Django 3.2.22 on 2023-10-21 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Training_plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_plan', models.CharField(max_length=100)),
                ('current_weight', models.FloatField()),
                ('target_weight_category', models.CharField(max_length=100)),
                ('sauna', models.BooleanField(default=False)),
                ('swimming', models.BooleanField(default=False)),
                ('private_trainer', models.BooleanField(default=False)),
                ('private_coaching_hours', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
