# Generated by Django 3.2.22 on 2023-10-21 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training_plan',
            name='training_plan',
            field=models.CharField(choices=[('basic', 'Basic Plan - Nrs 1000'), ('intermediate', 'Intermediate Plan - Nrs 2000'), ('advanced', 'Advanced Plan - Nrs 3000')], max_length=20),
        ),
    ]
